version: '3.5'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - 'db:/var/lib/postgresql/data'
      - ./tmp:/temp
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
  webpacker:
    build:
      context: ../../
      dockerfile: ./docker/development/Dockerfile
    env_file:
      - '../../.env'
    command: bash -c "rm -rf ./public/packs; (yarn check || yarn install) && ./bin/webpack-dev-server"
    volumes:
      - bundle:/bundle
      - .:/usr/src/app
    ports:
      - '3035:3035'
  web:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    command: /bin/bash -c 'rm -rf ./tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - bundle:/bundle
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    env_file:
      - '../../.env'
    depends_on:
      - db
      - redis
      - webpacker
volumes:
  db:
  es_data:
  bundle:
  tmp:
