detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2
  LongParameterList:
    max_params: 4
directories:
  "app/workers":
    UtilityFunction:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
