detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2
  LongParameterList:
    max_params: 4
  TooManyStatements:
    max_statements: 10
  UtilityFunction:
    exclude:
      - "Youtube::Client"
      - "BotTelegram::MessagesManager"
      - "BotTelegram::Leopold::ItWayPro::WordsCheck"
      - "BotTelegram::Leopold::Commands"
      - "BotTelegram::Info"
      - "MultiProjectCallbacks"
  FeatureEnvy:
    exclude:
      - "BotTelegram::MessagesManager#message_to_user"
      - "MultiProjectConfigurationMiddleware"
  NestedIterators:
    max_allowed_nesting: 2
directories:
  "app/workers":
    UtilityFunction:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
