Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
  Include:
    - spec/
Metrics/AbcSize:
  Max: 18
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/stage
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
AllCops:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/seeds.rb
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
  TargetRubyVersion: 2.5
