Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
  Include:
    - spec/
Metrics/AbcSize:
  Max: 35
Metrics/MethodLength:
  Max: 20
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - bin/*
    - config/application.rb
    - lib/middleware/**/*.rb
    - spec/support/capybara_helpers/node/element.rb
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/stage
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Style/MixinUsage:
  Exclude:
    - bin/*
Metrics/PerceivedComplexity: 
  Max: 9
Metrics/CyclomaticComplexity:
  Max: 8
Style/AsciiComments:
  Exclude:
    - spec/**/*.rb
AllCops:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/seeds.rb
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
  TargetRubyVersion: 2.7
