version: '3.8'
services:  
  app:    
    image: "kalashnikovisme/tramway_pro:develop"
    depends_on:      
      - db  
    environment:
      - RUBY_VERSION=3.2.1
      - RAILS_DB_PRODUCTION=tramway_pro_test
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command: sh /home/tramway/app/exec.sh
  db:    
    image: postgres:15
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_ROOT=/home/tramway/app/
    ports:
      - 5432:5432
  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    restart: always
    depends_on:      
      - app    
    ports:      
      - 80:80
      - 443:443

volumes:  
  postgres_data:
