version: '3.8'
services:  
  app:    
    image: "kalashnikovisme/tramway_pro:develop"
    depends_on:      
      - db  
      - redis
    environment:
      - RUBY_VERSION=3.2.1
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - ERRBIT_PROJECT_KEY=${ERRBIT_PROJECT_KEY}
    command: sh /home/tramway/app/run.sh
    volumes:
      - ./public/system:/home/tramway/app/public/system
      - ./public/uploads:/home/tramway/app/public/uploads
      - ./log:/home/tramway/app/log/
      - ./tmp:/home/tramway/app/tmp/
    ports:
      - 9292:9292
  db:    
    image: postgres:15
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
      - ./dumps:/dumps
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    restart: always
    depends_on:      
      - app    
    ports:      
      - 80:80
      - 443:443
    volumes:
      - ./public:/var/www/tramway_pro/public
volumes:  
  postgres_data:
