version: '3.8'
services:  
  app:    
    image: "kalashnikovisme/tramway_pro:develop"
    depends_on:      
      - db  
    environment:
      - RUBY_VERSION=3.2.1
      - RAILS_DB_PRODUCTION=tramway_pro_test
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: sh /home/tramway/app/exec.sh
  db:    
    image: postgres:15
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    depends_on:      
      - app    
    ports:      
      - 80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:  
  postgres_data:
