- hosts: production
  vars_files:
    - production.yml
  tasks:
    - name: Ping to server
      shell: echo 'Ready to deploy!'
      register: ping

    - name: Checking ping
      debug:
        msg: "{{ ping.stdout }}"

    - name: Getting timestamp
      command: date +%Y%m%d%H%M%S
      register: time

    - name: Save application path
      set_fact:
        release_path: "{{ app_path }}/releases/{{ time.stdout }}"

    - name: Checking application path
      debug:
        msg: "Current application path is {{ release_path }}"

    - name: Checking out repo
      git: repo=https://github.com/Purple-Magic/tramway_pro
           dest={{ release_path }}
           version=master

    - name: Linking config files
      file:
        src={{ shared_path }}/config/{{ item }}
        dest={{ release_path }}/config/{{ item }}
        state=link
        force=yes
      with_items:
        - database.yml
        - secrets.yml
        - sidekiq.yml

    - name: Create tmp
      file:
        path={{ release_path }}/tmp
        state=directory
        force=yes

    - name: Remove old logs
      file:
        path={{ release_path }}/log
        state=absent

    - name: Linking directories
      file:
        src={{ shared_path }}/{{ item }}
        dest={{ release_path }}/{{ item }}
        state=link
      with_items:
        - .env
        - log
        - tmp/pids
        - tmp/cache
        - tmp/sockets
        - vendor/bundle
        - public/system
        - public/uploads
        - public/podcasts
        - node_modules

    - name: Bundle
      shell: "/usr/share/rvm/bin/rvm {{ ruby_version }} do bundle install"
      args:
        chdir: "{{ release_path }}"

    - name: YARN install
      shell: "cd {{ release_path }} && /bin/bash -ilc 'yarn'"
      args:
        chdir: "{{ release_path }}"

    - name: Update browserlist
      shell: "cd {{ release_path }} && /bin/bash -ilc 'npx browserslist@latest --update-db'"
      args:
        chdir: "{{ release_path }}"

    - name: Assets clean
      shell: "/bin/bash -lic '/usr/share/rvm/bin/rvm {{ ruby_version }} do bundle exec rails assets:clean'"
      args:
        chdir: "{{ release_path }}"

        #- name: Assets precompile
        #shell: "/bin/bash -lic '/usr/share/rvm/bin/rvm {{ ruby_version }} do bundle exec rails assets:precompile'"
        #args:
        #chdir: "{{ release_path }}"

    - name: Migrate
      shell: "/bin/bash -lic '/usr/share/rvm/bin/rvm {{ ruby_version }} do {{ release_path }}/bin/rake db:migrate'"
      args:
        chdir: "{{ release_path }}"

    - name: Linking current
      file:
        src={{ release_path }}
        dest={{ app_path }}/current
        state=link
        force=yes
