- name: Stop unicorn
  shell: "[ -e /srv/tramway_pro/shared/tmp/pids/unicorn.pid  ] && kill `cat /srv/tramway_pro/shared/tmp/pids/unicorn.pid`"
  ignore_errors: yes

- name: Start unicorn
  shell: "/bin/bash -ilc '/usr/share/rvm/bin/rvm {{ ruby_version }} do bundle exec unicorn -c /srv/tramway_pro/current/config/unicorn/production.rb -E production -D'"
  args:
    chdir: "{{ app_path }}/current"

- name: Stop sidekiq
  ignore_errors: yes
  shell: "ps aux | grep -ie sidekiq | awk '{print $2}' | xargs kill -9 "

- name: Start sidekiq
  shell: "/bin/bash -ilc '/usr/share/rvm/bin/rvm {{ ruby_version }} do bundle exec sidekiq -d' &"
  args:
    chdir: "{{ app_path }}/current"
