version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - 'db:/var/lib/postgresql/data'
      - ./tmp:/temp
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
  webpacker:
    build:
      context: ../
      dockerfile: ./docker/development/Dockerfile
    env_file:
      - '../.env'
    command: bash -c "rm -rf ./public/packs; (yarn check || yarn install) && ./bin/webpack-dev-server"
    volumes:
      - bundle:/bundle
      - .:/usr/src/app
    ports:
      - '3035:3035'
volumes:
  db:
  bundle:
  