default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tramway_pro_development
test:
  <<: *default
  database: tramway_pro_test
production:
  <<: *default
  database: <%= ENV["RAILS_DB_PRODUCTION"] %>
