development:
  sportschool_ulsk: sportschool-ulsk.test
  it_way: it-way.test
  kalashnikovisme: kalashnikovisme.test
  tramway_dev: tramway.test
  engineervol: engineervol.test
  listai: listai.test
  purple_magic: purple-magic.test
  gorodsad73: gorodsad73.test
  dobry_sosed: dobry-sosed.test
  engines:
    'sportschool-ulsk.test': sport_school
    'it-way.test': conference
    'kalashnikovisme.test': site
  application_class:
    'tramway.test': tramway_dev
    'listai.test': listai_app
  application:
    'engineervol.test':
      name: engineervol
      title: Инженерное волонтёрство
    'gorodsad73.test':
      name: gorodsad73
      title: Город-сад
      public_name: Город-сад
      tagline: Ландшафтный дизайн - как искусство
    'dobry-sosed.test':
      name: dobry_sosed
      title: Добрый сосед
      public_name: Добрый сосед
    'purple-magic.test':
      name: purple_magic
      title: PurpleMagic
      public_name: PurpleMagic


production:
  sportschool_ulsk: sportschool-ulsk.ru
  it_way: it-way.pro
  kalashnikovisme: kalashnikovisme.ru
  engineervol: engineervol.ru
  tramway_dev: tramway.pro
  listai: listai.io
  purple_magic: purple-magic.com
  gorodsad73: gorodsad73.ru
  engines:
    'sportschool-ulsk.ru': sport_school
    'it-way.pro': conference
    'kalashnikovisme.ru': site
  application_class:
    'tramway.pro': tramway_dev
    'listai.io': listai_app
  application:
    'engineervol.ru':
      name: engineervol
      title: Инженерное волонтёрство
    'gorodsad73.ru':
      name: gorodsad73
      title: Город-сад 
      public_name: Город-сад
      tagline: Ландшафтный дизайн - как искусство
    'purple-magic.com':
      name: purple_magic
      title: PurpleMagic
      public_name: PurpleMagic

test:
  sportschool_ulsk: sportschool-ulsk.test
  it_way: it-way.test
  kalashnikovisme: kalashnikovisme.test
  tramway_dev: tramway.test
  engineervol: engineervol.test
  listai: listai.test
  purple_magic: purple-magic.test
  gorodsad73: gorodsad73.test
  engines:
    'sportschool-ulsk.test': sport_school
    'it-way.test': conference
    'kalashnikovisme.test': site
  application_class:
    'tramway.test': tramway_dev
    'listai.test': listai_app
    'purple-magic.test': purple_magic
  application:
    'engineervol.test':
      name: engineervol
    'gorodsad73.test':
      name: gorodsad73
      title: Город-сад
      public_name: Город-сад
      tagline: Ландшафтный дизайн - как искусство
    'purple-magic.test':
      name: purple_magic
      title: PurpleMagic
      public_name: PurpleMagic
