purple_magic: &purple_magic
  name: purple_magic
  title: PurpleMagic
  public_name: PurpleMagic
  favicon: '/purple-magic.ico'

red_magic: &red_magic
  name: red_magic
  title: RedMagic
  public_name: RedMagic
  favicon: '/red-magic.ico'

development:
  it_way: it-way.test
  kalashnikovisme: kalashnikovisme.test
  tramway_dev: tramway.test
  engineervol: engineervol.test
  listai: listai.test
  purple_magic: purple-magic.test
  gorodsad73: gorodsad73.test
  dobry_sosed: dobry-sosed.test
  red_magic: red-magic.test
  engines:
    'it-way.test': conference
    'kalashnikovisme.test': site
  application_class:
    'tramway.test': tramway_dev
    'listai.test': listai_app
  application:
    'engineervol.test':
      name: engineervol
      title: Инженерное волонтёрство
    'gorodsad73.test':
      name: gorodsad73
      title: Город-сад
      public_name: Город-сад
      tagline: Ландшафтный дизайн - как искусство
    'purple-magic.test':
      <<: *purple_magic
    'red-magic.test':
      <<: *red_magic

production:
  it_way: it-way.pro
  kalashnikovisme: kalashnikovisme.ru
  engineervol: engineervol.ru
  tramway_dev: tramway.pro
  listai: listai.io
  purple_magic: purple-magic.com
  gorodsad73: gorodsad73.ru
  red_magic: red-magic.ru
  engines:
    'it-way.pro': conference
    'kalashnikovisme.ru': site
  application_class:
    'tramway.pro': tramway_dev
    'listai.io': listai_app
  application:
    'engineervol.ru':
      name: engineervol
      title: Инженерное волонтёрство
    'gorodsad73.ru':
      name: gorodsad73
      title: Город-сад 
      public_name: Город-сад
      tagline: Ландшафтный дизайн - как искусство
    'purple-magic.com':
      <<: *purple_magic
    'red-magic.com':
      <<: *red_magic

test:
  it_way: it-way.test
  kalashnikovisme: kalashnikovisme.test
  tramway_dev: tramway.test
  engineervol: engineervol.test
  listai: listai.test
  purple_magic: purple-magic.test
  gorodsad73: gorodsad73.test
  red_magic: red-magic.test
  engines:
    'it-way.test': conference
    'kalashnikovisme.test': site
  application_class:
    'tramway.test': tramway_dev
    'listai.test': listai_app
    'purple-magic.test': purple_magic
  application:
    'engineervol.test':
      name: engineervol
    'gorodsad73.test':
      name: gorodsad73
      title: Город-сад
      public_name: Город-сад
      tagline: Ландшафтный дизайн - как искусство
    'purple-magic.test':
      <<: *purple_magic
    'red-magic.test':
      <<: *red_magic
