purple_magic: &purple_magic
  name: purple_magic
  title: PurpleMagic
  public_name: PurpleMagic
  favicon: '/purple-magic.ico'

red_magic: &red_magic
  name: red_magic
  title: RedMagic
  public_name: RedMagic
  favicon: '/red-magic.ico'

kalashnikovisme: &kalashnikovisme
  name: kalashnikovisme
  title: Kalashnikovisme
  public_name: "kalashnikovisme"

benchkiller: &benchkiller
  name: benchkiller
  title: BenchKiller
  public_name: "BenchKiller"

development:
  it_way: it-way.test
  kalashnikovisme: kalashnikovisme.test
  tramway_dev: tramway.test
  engineervol: engineervol.test
  listai: listai.test
  purple_magic: purple-magic.test
  dobry_sosed: dobry-sosed.test
  red_magic: red-magic.test
  benchkiller: freedvs.test
  engines:
    'it-way.test': conference
  application_class:
    'tramway.test': tramway_dev
    'listai.test': listai_app
  application:
    'engineervol.test':
      name: engineervol
      title: Инженерное волонтёрство
    'purple-magic.test':
      <<: *purple_magic
    'red-magic.test':
      <<: *red_magic
    'kalashnikovisme.test':
      <<: *kalashnikovisme
    'freedvs.test':
      <<: *benchkiller

production:
  it_way: it-way.pro
  kalashnikovisme: kalashnikovisme.ru
  engineervol: engineervol.ru
  tramway_dev: tramway.pro
  listai: listai.io
  purple_magic: purple-magic.com
  red_magic: red-magic.ru
  benchkiller: freedvs.com
  engines:
    'it-way.pro': conference
  application_class:
    'tramway.pro': tramway_dev
    'listai.io': listai_app
  application:
    'engineervol.ru':
      name: engineervol
      title: Инженерное волонтёрство
    'purple-magic.com':
      <<: *purple_magic
    'red-magic.ru':
      <<: *red_magic
    'kalashnikovisme.ru':
      <<: *kalashnikovisme
    'freedvs.com':
      <<: *benchkiller

test:
  it_way: it-way.test
  kalashnikovisme: kalashnikovisme.test
  tramway_dev: tramway.test
  engineervol: engineervol.test
  listai: listai.test
  purple_magic: purple-magic.test
  red_magic: red-magic.test
  benchkiller: freedvs.test
  engines:
    'it-way.test': conference
  application_class:
    'tramway.test': tramway_dev
    'listai.test': listai_app
    'purple-magic.test': purple_magic
  application:
    'engineervol.test':
      name: engineervol
    'purple-magic.test':
      <<: *purple_magic
    'red-magic.test':
      <<: *red_magic
    'kalashnikovisme.test':
      <<: *kalashnikovisme
    'freedvs.test':
      <<: *benchkiller
