leopold_send_chat_quest_stats:
  cron: "0 0 * * 1"
  class: LeopoldSendChatQuestsStats
  queue: bot

leopold_send_everyday_report:
  cron: "0 7 * * *"
  class: LeopoldSendEverydayReportJob
  queue: bot

benchkiller_send_planned_notifications:
  cron: "* * * * *"
  class: BenchkillerSendPlannedNotifications 
  queue: benchkiller

benchkiller_send_planned_notifications:
  cron: "5 17 * * *"
  class: LeopoldSendItWayHistoryJob
  queue: bot

it_way_generate_twitter_previews:
  cron: "0 0 * * 1"
  class: ItWayGenerateTwitterPreviews
  queue: it_way
