on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundle-cache: true

      - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Build App
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          cp config/database.sample.yml config/database.yml
          cp config/secrets.sample.yml config/secrets.yml
          bin/rails db:setup
  run_tests:
    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec
#  notification:
#    steps:
#      - name: Rocket.Chat Notification
#        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
#        if: always()
#        with:
#          type: ${{ job.status }}
#          job_name: '*Lint Check*'
#          mention: 'here'
#          mention_if: 'failure'
#          channel: '#random'
#          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
#        commit: true
#      token: ${{ secrets.GITHUB_TOKEN }}
