on:
  push:
    branches:
      - master
      - develop
      - feature/add_reek
  pull_request:
    branches:
      - master
      - develop
jobs:
   syntax_check:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v1

       - name: Set up Ruby 2.7
         uses: actions/setup-ruby@v1
         with:
           ruby-version: 2.7
           bundle-cache: true

       - name: Run syntax check
         run: |
           mkdir /tmp/syntax-check-results
           find app bin config db lib spec -type f -name "*.rb" -o -name "*.rake" | xargs -l -P 0 -I{} ruby -c {} 1> /dev/null 2> >(tee -a /tmp/syntax-check-results.txt >&2)

   smell_check:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v1

       - name: Set up Ruby 2.7
         uses: actions/setup-ruby@v1
         with:
           ruby-version: 2.7
           bundle-cache: true

       - name: Install reek
         run: |
           gem install reek -v '6.0.6'

       - name: Show reek version
         run: |
           reek -v

       - name: Run smell check
         run: |
           reek -c .reek.yml .

       - name: Rocket.Chat Notification
         uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
         if: always()
         with:
           username: bot_leopold
           type: ${{ job.status }}
           job_name: '*Tramway Pro Smell Check*'
           mention: 'here'
           channel: 'dNei2bg5ufmQFdFWx'
           url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
           commit: true
           token: ${{ secrets.GITHUB_TOKEN }}

   rubocop:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v1

       - name: Set up Ruby 2.7
         uses: actions/setup-ruby@v1
         with:
           ruby-version: 2.7
           bundle-cache: true

       - name: Install rubocop
         run: |
           gem install rubocop

       - name: Running Linter
         run:
           rubocop

       - name: Rocket.Chat Notification
         uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
         if: always()
         with:
           username: bot_leopold
           type: ${{ job.status }}
           job_name: '*Tramway Pro Linter*'
           mention: 'here'
           channel: 'dNei2bg5ufmQFdFWx'
           url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
           commit: true
           token: ${{ secrets.GITHUB_TOKEN }}

  tests: 
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundle-cache: true

      - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Install gems
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup application
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          CHROME_DRIVER_VERSION: 98.0.4758.102
        run: |
          echo "127.0.0.1 it-way.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 kalashnikovisme.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 tramway.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 engineervol.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 listai.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 purple-magic.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 red-magic.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 freedvs.test" | sudo tee -a /etc/hosts
          cp config/database.sample.yml config/database.yml
          cp config/secrets.sample.yml config/secrets.yml
          bin/rails db:create db:migrate db:seed
          bin/rails parallel:setup
          bundle exec rspec
          #parallel_rspec --verbose -s spec/features/podcast/episodes/actions/render_video_spec.rb -s spec/features/bot/quests/scenario_spec.rb -i --fail-fast

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          username: bot_leopold
          type: ${{ job.status }}
          job_name: '*Tramway Pro Tests*'
          mention: 'here'
          channel: 'dNei2bg5ufmQFdFWx'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
